import Thumbnail1 from "../../asset/images/1.jpg";
import Thumbnail2 from "../../asset/images/2.jpg";
import Thumbnail3 from "../../asset/images/3.jpg";

export default [
        {
                rating: 3,
                views: "1.7k",
                duration: "12:03",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "7 days ago",
                thumbnail: Thumbnail1,
                viewPercent: 30,
        },
        {
                rating: 2,
                views: "145",
                duration: "1:00",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "2 days ago",
                thumbnail: Thumbnail2,
                viewPercent: 0,
        },
        {
                rating: 5,
                views: "1k",
                duration: "5:30",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "14 days ago",
                thumbnail: Thumbnail3,
                viewPercent: 50,
        },
        {
                rating: 3,
                views: "1.7k",
                duration: "12:03",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "7 days ago",
                thumbnail: Thumbnail1,
                viewPercent: 30,
        },
        {
                rating: 2,
                views: "145",
                duration: "1:00",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "2 days ago",
                thumbnail: Thumbnail2,
                viewPercent: 0,
        },
        {
                rating: 5,
                views: "1k",
                duration: "5:30",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "14 days ago",
                thumbnail: Thumbnail3,
                viewPercent: 50,
        },
        {
                rating: 3,
                views: "1.7k",
                duration: "12:03",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "7 days ago",
                thumbnail: Thumbnail1,
                viewPercent: 30,
        },
        {
                rating: 2,
                views: "145",
                duration: "1:00",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "2 days ago",
                thumbnail: Thumbnail2,
                viewPercent: 0,
        },
        {
                rating: 5,
                views: "1k",
                duration: "5:30",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "14 days ago",
                thumbnail: Thumbnail3,
                viewPercent: 50,
        },
        {
                rating: 3,
                views: "1.7k",
                duration: "12:03",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "7 days ago",
                thumbnail: Thumbnail1,
                viewPercent: 30,
        },
        {
                rating: 2,
                views: "145",
                duration: "1:00",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "2 days ago",
                thumbnail: Thumbnail2,
                viewPercent: 0,
        },
        {
                rating: 5,
                views: "1k",
                duration: "5:30",
                details: "Sjgfsdf  jdfye djf d rtuw    js sjdfger jdfhgsf87we js sde sdjhfgswet sj sfjsgffwfe jshdgfs sdgfsgfjs er dgfjsg ",
                title: "Crash Course",
                postedOn: "14 days ago",
                thumbnail: Thumbnail3,
                viewPercent: 50,
        }
];